config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :values
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  
  root 'main#index'

  namespace :api, defaults: { format: :json } do
      
    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get
  end


 # get 'work/index'
  #get 'work/choose_theme'
  #get 'work/display_theme'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #root 'main#index' при аут. вернуть
  match 'index', to: 'main#index',           via: 'get'
  match 'about', to: 'main#about',           via: 'get'
  match 'help', to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'
 
  match 'work',     to: 'work#index',           via: 'get'
  match 'choose_theme', to: 'work#choose_theme', via: 'get'
  match 'display_theme', to: 'work#display_theme', via: 'post'

  match 'signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  match 'results_list', to: 'work#results_list', via: 'get'
  match 'save_value', to: 'api/api#save_value',   via: 'get'
end

#ApiDemoApp::Application.routes.draw do
#  scope '/api' do
#   scope '/v1' do
#     scope '/projects' do
#        get '/' => 'api_projects#index'
#        post '/' => 'api_projects#create'
#        
#        scope '/names' do
#          get '/' => 'api_names#index'
#          post '/' => 'api_names#create'
#        end
#      end
#    end
#  end
#end

app/models/user.rb
class User < ApplicationRecord
    has_many :values, dependent: :destroy
    before_save { self.email = email.downcase }
    # before_save { email.downcase! } # alternative
    before_create :create_remember_token

    validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
    # validates :email, presence: true, uniqueness: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
    validates :password, length: { minimum: 6 }

    def User.new_remember_token
        SecureRandom.urlsafe_base64
    end

    def User.encrypt(token)
        Digest::SHA1.hexdigest(token.to_s)
    end

    private

    def create_remember_token
        self.remember_token = User.encrypt(User.new_remember_token)
    end
        
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name, t('.name')
    = f.text_field :name
  .field
    = f.label :email, t('.email')
    = f.email_field :email
  .field
    = f.label :password, t('.password')
    = f.password_field :password
  .field
    = f.label :password_confirmation, t('.password_confirmation')
    = f.password_field :password_confirmation

  .actions
    = f.submit t(".create_account"), class: "btn btn-large btn-primary"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
= render 'form'

= link_to 'Back', index_path, class: "btn btn-default"

app/views/users/show.html.haml
.container.h-100.mt-3.show_user
  .row.d-flex.justify-content-center.align-items-center.h-100
    .col-lg-12.col-xl-11
      .card.text-black{style: "border-radius: 25px;"}
        .card-body.p-md-5
          .row.justify-content-center
            .col-md-10.col-lg-6.col-xl-5.order-2.order-lg-1
              %p.text-center.h1.fw-bold.mb-5.mx-1.mx-md-4.mt-4
                = t('.title')
              .d-flex.flex-row.align-items-center.mb-4
                %b.me-3= t('.avatar')
                = gravatar_for @user
              .d-flex.flex-row.align-items-center.mb-4
                %b.me-3= t('.name')
                = @user.name
              .d-flex.flex-row.align-items-center.mb-4
                %b.me-3= t('.email')
                = @user.email
              .d-flex.justify-content-center.mx-4.mb-3.mb-lg-4
                - if signed_in?
                  = link_to t('.work'), work_path, class:"btn btn-lg btn-dark"
                - else
                  = link_to t('.sign_in'), signin_path, class:"btn btn-lg btn-dark"