config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :values
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  
  root 'main#index'

  namespace :api, defaults: { format: :json } do
      
    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get
  end


 # get 'work/index'
  #get 'work/choose_theme'
  #get 'work/display_theme'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #root 'main#index' при аут. вернуть
  match 'index', to: 'main#index',           via: 'get'
  match 'about', to: 'main#about',           via: 'get'
  match 'help', to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'
 
  match 'work',     to: 'work#index',           via: 'get'
  match 'choose_theme', to: 'work#choose_theme', via: 'get'
  match 'display_theme', to: 'work#display_theme', via: 'post'

  match 'signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  match 'results_list', to: 'work#results_list', via: 'get'
  match 'save_value', to: 'api/api#save_value',   via: 'get'
end

#ApiDemoApp::Application.routes.draw do
#  scope '/api' do
#   scope '/v1' do
#     scope '/projects' do
#        get '/' => 'api_projects#index'
#        post '/' => 'api_projects#create'
#        
#        scope '/names' do
#          get '/' => 'api_names#index'
#          post '/' => 'api_names#create'
#        end
#      end
#    end
#  end
#end

app/views/shared/_footer.html.haml
.container
  %footer.d-flex.flex-wrap.justify-content-between.align-items-center.py-3.my-4.border-top
    %ul.nav.col-md-4.justify-content-end
      %li.nav-item
        %a.nav-link.px-2.text-muted{:href => about_path} 
          = t('.about')
      %li.nav-item
        %a.nav-link.px-2.text-muted{:href => contacts_path} 
          = t('.contact')

app/views/shared/_header.html.haml
%header
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{type: "button", "data-toggle": "collapse", "data-target": "#alignment-example", "aria-expanded": "false"}
          %span.sr-only
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{"aria-current" => "page", href: index_path}= t('.home')

      .collapse.navbar-collapse#alignment-example
        %ul.nav.navbar-nav
          %li.nav-item
            %a.nav-link{href: help_path}= t('.help')
            
      %ul.navbar-nav.flex-row.d-none.d-md-flex.mt-2
        %li.nav-item.me-3.me-lg-1
          = link_to image_tag("russia.jpg", alt: "", height: "40", width: "40", class: "d-inline-block align-top me-2", title: "Русский" ),
          locale: :ru, class: "dropdown-item"
        %li.nav-item.mb-2.mb-lg-0
          = link_to image_tag("united-kingdom.jpg", alt: "", height: "40", width: "40", class: "d-inline-block align-top me-2", title: "English" ),
          locale: :en, class: "dropdown-item"
        %li.nav-item.me-3.me-lg-1
          %p.nav-link.me-2= I18n.locale  
      
      %ul.navbar-nav.flex-row.ml-auto
        - if signed_in?
          = gravatar_for current_user
          %li.nav-item.logged.me-3.me-lg-1.mt-2
            %p= link_to @current_user.email, current_user, class: "nav-link me-2", title: "Watch profile info"
          %li.nav-item.me-3.me-lg-1.mt-3
            = link_to t('.sign_out'), signout_path, method: "delete", class: "link-secondary"
        - else
          %li.nav-item.me-3.me-lg-1
            = link_to t('.sign_in'), signin_path, class: "btn btn-outline-light me-2"
          %li.nav-item.me-3.me-lg-1
            = link_to t('.sign_up'), signup_path, class: "btn btn-outline-light"