config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :values
  resources :images
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  
  root 'main#index'

  namespace :api, defaults: { format: :json } do
      
    match 'next_image',       to: 'api#next_image',   via: 'get'
    match 'prev_image',       to: 'api#prev_image',   via: 'get'
    match 'save_value',       to: 'api#save_value',   via: :get
  end


 # get 'work/index'
  #get 'work/choose_theme'
  #get 'work/display_theme'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  #root 'main#index' при аут. вернуть
  match 'index', to: 'main#index',           via: 'get'
  match 'about', to: 'main#about',           via: 'get'
  match 'help', to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'
 
  match 'work',     to: 'work#index',           via: 'get'
  match 'choose_theme', to: 'work#choose_theme', via: 'get'
  match 'display_theme', to: 'work#display_theme', via: 'post'

  match 'signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  match 'results_list', to: 'work#results_list', via: 'get'
  match 'save_value', to: 'api/api#save_value',   via: 'get'
end

#ApiDemoApp::Application.routes.draw do
#  scope '/api' do
#   scope '/v1' do
#     scope '/projects' do
#        get '/' => 'api_projects#index'
#        post '/' => 'api_projects#create'
#        
#        scope '/names' do
#          get '/' => 'api_names#index'
#          post '/' => 'api_names#create'
#        end
#      end
#    end
#  end
#end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :theme
    scope :theme_images, -> (theme_id) {
        select('id', 'name', 'file', 'ave_value').where(theme_id: theme_id)
  }

    # find image by id
    scope :find_image, -> (image_id) {
		 find(image_id) 
    }

    #ave_value
    def self.update_ave_value(image_id, ave_value)
        image = find(image_id)
        image.update(ave_value: ave_value)
    end

    # Refactored method - transferred from work_image.rb module
    def self.show_valued_image(new_value_data)
        image_id = new_value_data[:image_id]
        theme_id = new_value_data[:theme_id]
        current_user_id = new_value_data[:user_id]
        user_valued, value = Value.user_valued_exists(current_user_id, image_id) # 1/0 ?
        values_qty = Value.all.count.round

        common_ave_value = user_valued == 1 ? find(image_id).ave_value.round : 0

        data = {
        values_qty: values_qty,
        current_user_id: current_user_id,
        theme_id: theme_id,
        image_id: image_id,
        user_valued: user_valued,
        value: value,
        common_ave_value: common_ave_value
        }
        # logger.info "In show_image:  data = #{data.inspect} "
        data
    end


    def self.value_and_update(new_value_data)
        image_id = new_value_data[:image_id]
        Value.create(new_value_data)
        ave_value = Value.calc_average_value(image_id).round
        # puts "in value_and_update: image_id = #{image_id}, ave_value = #{ave_value} \n"
        update_ave_value(image_id, ave_value)
    
        show_valued_image(new_value_data)
    end

end




    

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy!

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name, :file, :ave_value, :theme_id)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.haml
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.text_field :file
  .field
    = f.label :ave_value
    = f.text_field :ave_value
  .field
    = f.label :theme_id
    = f.number_field :theme_id
  .actions
    = f.submit 'Save'

app/views/images/_images.html.haml
.col-md-9
  .image_display
    .row.image
      .col-md-12
        %h2.up-theme{title: t('.theme_name')}
          #{@selected_theme}
      .col-md-12
        %h2.up{title: "Image file name"}
          #{@selected_image_name}
      .col-md-1
        .img-left-side
          %h3{title: "list to previous image"}
            %i.fa.fa-chevron-circle-left.strong
      .col-md-10
        .img-center{title: "Default image"}
          %img{alt: "Default Image", src: 'assets/pictures/default.jpg', title: "Default image", style: "width:100%; height:100%;"}
          .image_user_value{title: "Expert value"}
      .col-md-10
        .img-center{title: "Default image"}
          %img{alt: "Default Image", src: 'assets/pictures/default.jpg', title: "Default image", style: "width:100%; height:100%;"}
          .image_user_value{title: "Expert value"}
      -#.img-title
      .col-md-1
        .img-right-side
          %h3{title: "list to next image"}
            %i.fa.fa-chevron-circle-right

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table
  %thead
    %tr
      %th Name
      %th File
      %th Ave value
      %th Theme
      %th
      %th
      %th

  %tbody
    - @images.each do |image|
      %tr
        %td= image.name
        %td= image.file
        %td= image.ave_value
        %td= image.theme_id
        %td= link_to 'Show', image
        %td= link_to 'Edit', edit_image_path(image)
        %td= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @image.name
%p
  %b File:
  = @image.file
%p
  %b Ave value:
  = @image.ave_value
%p
  %b Theme:
  = @image.theme_id

= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path